CREATE DATABASE SALARYINFORMATION ON PRIMARY (
    NAME = 'TRACKSALARY',
    FILENAME = 'E:\COFRGE\B5DB\SALARIES.MDF',
    SIZE = 3MB,
    MAXSIZE = 20MB,
    FILEGROWTH = 2 %
) LOG ON (
    NAME = 'SALLOGS',
    FILENAME = 'E:\COFRGE\B5DB\SALARYLOGS.LDF',
    SIZE = 3MB,
    MAXSIZE = 25MB,
    FILEGROWTH = 2 %
);

USE SALARYINFORMATION;

CREATE TABLE DEPARTMENT (
    DEPARTMENT_ID INT IDENTITY (1101, 1) PRIMARY KEY,
    DEPARTMENT_NAME VARCHAR(30) NOT NULL
);

INSERT INTO
    DEPARTMENT (DEPARTMENT_NAME)
VALUES
('HUMAN RESOURCES'),
    ('ADMINISTRATION'),
    ('FINANACE AND ACCOUNTS'),
    ('TRAINING AND DEVELOPMENT'),
    ('IT-SOFTWARE'),
    ('MARKETING');

SELECT
    *
FROM
    DEPARTMENT;

CREATE TABLE EMPLOYEE (
    EMPLOYEE_ID INT IDENTITY (101, 21) PRIMARY KEY,
    EMPLOYEE_NAME VARCHAR(30) NOT NULL,
    GENDER CHAR,
    DEPARTMENT_ID INT,
    POSITION NVARCHAR(MAX) NOT NULL,
    CONSTRAINT FK_EMPLOYEE_JOB FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT (DEPARTMENT_ID),
    CONSTRAINT CK_EMP_GENDER CHECK (GENDER IN ('M', 'F'))
);

ALTER TABLE
    EMPLOYEE
ALTER COLUMN
    POSITION NVARCHAR(MAX) NULL;

INSERT INTO
    EMPLOYEE (EMPLOYEE_NAME, GENDER, DEPARTMENT_ID, POSITION)
VALUES
('AKASH', 'M', 1105, 'DEVELOPER'),
    ('VIMALA', 'F', 1103, 'ACCOUNTANT'),
    ('GNANASEKARAN', 'M', 1104, 'TRAINER'),
    ('RASHI', 'F', 1104, 'SR. TRAINER'),
    ('VIKASH', 'M', 1103, 'ACCOUNTS EXECUTIVE'),
    ('ARUNYA', 'F', NULL, NULL),
    ('RUPA', 'F', NULL, NULL);

SELECT
    EMPLOYEE_ID,
    EMPLOYEE_NAME
FROM
    EMPLOYEE
WHERE
    POSITION IS NOT NULL;

CREATE TABLE SALARY (
    EMPLOYEE_ID INT,
    BASIC_PAY MONEY,
    TOTAL_ALLOWANCES MONEY,
    TOTAL_DEDUCTIONS MONEY,
    GROSS_SALARY MONEY,
    NET_TAKE_HOME MONEY,
    CONSTRAINT FK_EMPLOYEE_SALARY FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE (EMPLOYEE_ID)
);

INSERT INTO
    SALARY (EMPLOYEE_ID)
SELECT
    *
FROM
    SALARY;

SELECT
    *
FROM
    EMPLOYEE
WHERE
    POSITION IS NULL;

SELECT
    EMPLOYEE_ID,
    EMPLOYEE_NAME,
    ISNULL(POSITION, 'NOT ALLOTTED')
FROM
    EMPLOYEE;

SELECT
    EMPLOYEE_ID,
    EMPLOYEE_NAME,
    COALESCE(POSITION, 'NOT APPLICABLE', 'NOT
ALLOWED')
FROM
    EMPLOYEE;

UPDATE
    SALARY
SET
    BASIC_PAY = 175000
WHERE
    EMPLOYEE_ID = 374
UPDATE
    SALARY
SET
    NET_TAKE_HOME = GROSS_SALARY - TOTAL_DEDUCTIONS;

SELECT
    EMPLOYEE_ID,
    SUM(BASIC_PAY) AS 'BASIC PAY'
FROM
    SALARY
WHERE
    BASIC_PAY <= 50000
GROUP BY
    (EMPLOYEE_ID)
SELECT
    E.EMPLOYEE_ID,
    E.EMPLOYEE_NAME,
    D.DEPARTMENT_NAME,
    S.NET_TAKE_HOME,
    SUM(S.BASIC_PAY) AS 'BASIC SALARY'
FROM
    EMPLOYEE E
    JOIN DEPARTMENT D ON (E.DEPARTMENT_ID = D.DEPARTMENT_ID)
    JOIN SALARY S ON (E.EMPLOYEE_ID = S.EMPLOYEE_ID)
WHERE
    E.GENDER = 'F'
    AND S.BASIC_PAY > 40000
GROUP BY
    E.EMPLOYEE_ID,
    E.EMPLOYEE_NAME,
    D.DEPARTMENT_NAME,
    S.NET_TAKE_HOME;

SELECT
    *
FROM
    EMPLOYEE
    CROSS JOIN DEPARTMENT
    CROSS JOIN SALARY;

SP_HELP EMPLOYEE;

CREATE CLUSTERED INDEX MYIDX ON SALARY(BASIC_PAY);

CREATE INDEX MYSALIDX ON SALARY(NET_TAKE_HOME);

CREATE VIEW MYSALVUE AS
SELECT
    *
FROM
    SALARY;

SELECT
    *
FROM
    SALARY;

SELECT
    *
FROM
    MYSALVUE
ORDER BY
    NET_TAKE_HOME;

DELETE FROM
    MYSALVUE
WHERE
    EMPLOYEE_ID = 248;

CREATE VIEW MYVIEW AS
SELECT
    E.EMPLOYEE_ID,
    E.EMPLOYEE_NAME,
    D.DEPARTMENT_NAME,
    S.NET_TAKE_HOME,
    SUM(S.BASIC_PAY) AS 'BASIC SALARY'
FROM
    EMPLOYEE E
    JOIN DEPARTMENT D ON (D.DEPARTMENT_ID = E.DEPARTMENT_ID)
    JOIN SALARY S ON (S.EMPLOYEE_ID = E.EMPLOYEE_ID)
GROUP BY
    E.EMPLOYEE_ID,
    E.EMPLOYEE_NAME,
    D.DEPARTMENT_NAME,
    S.NET_TAKE_HOME
HAVING
    SUM(S.BASIC_PAY) > 50000;

SELECT
    *
FROM
    MYVIEW;

BEGIN
SELECT
    *
FROM
    EMPLOYEE;

END;

GO
    DECLARE @EID INT;

BEGIN
SET
    @EID = 248
SELECT
    *
FROM
    EMPLOYEE
WHERE
    EMPLOYEE_ID = @EID;

END;

GO
    CREATE PROCEDURE MYPROC AS DECLARE @TAKE_HOME MONEY BEGIN
SET
    @TAKE_HOME = 100000
SELECT
    *
FROM
    SALARY
WHERE
    NET_TAKE_HOME >= @TAKE_HOME;

END
GO
    EXEC MYPROC;

SELECT
    LEN(EMPLOYEE_NAME) AS 'CHAR LENGTH'
FROM
    EMPLOYEE;

SELECT
    EMPLOYEE_NAME,
    SUBSTRING(EMPLOYEE_NAME, 5, 7) AS 'SUBSTRING'
FROM
    EMPLOYEE;

SELECT
    REVERSE(EMPLOYEE_NAME) AS 'REVERSED NAME'
FROM
    EMPLOYEE;

ALTER TABLE
    EMPLOYEE
ADD
    DATE_OF_BIRTH DATETIME;

UPDATE
    EMPLOYEE
SET
    DATE_OF_BIRTH = '1972-05-26'
WHERE
    EMPLOYEE_NAME = 'GNANASEKARAN';

SELECT
    EMPLOYEE_NAME,
    DATE_OF_BIRTH
FROM
    EMPLOYEE;

SELECT
    GETDATE() AS TODAY;

SELECT
    MONTH(GETDATE()) AS 'CURRENT MONTH'
SELECT
    *
FROM
    SALARY;

SELECT
    EMPLOYEE_ID,
    BASIC_PAY,
    ROW_NUMBER() OVER (
        PARTITION BY BASIC_PAY
        ORDER BY
            EMPLOYEE_ID
    ) AS 'ROW NUMBER'
FROM
    SALARY;

SELECT
    EMPLOYEE_ID,
    BASIC_PAY,
    GROSS_SALARY,
    NET_TAKE_HOME,
    RANK() OVER (
        ORDER BY
            BASIC_PAY ASC
    ) AS 'SALARY RANK'
FROM
    SALARY;

SELECT
    EMPLOYEE_ID,
    BASIC_PAY,
    GROSS_SALARY,
    NET_TAKE_HOME,
    DENSE_RANK() OVER (
        ORDER BY
            BASIC_PAY ASC
    ) AS 'SALARY RANK'
FROM
    SALARY;

SELECT
    EMPLOYEE_ID,
    BASIC_PAY,
    GROSS_SALARY,
    NET_TAKE_HOME,
    NTILE(7) OVER (
        ORDER BY
            BASIC_PAY ASC
    ) AS 'NTILE'
FROM
    SALARY;

SELECT
    *
FROM
    EMPLOYEE;